/*
 * This file is generated by jOOQ.
 */
package com.hometask.moneytransfer.model.db.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Account implements Serializable {

    private static final long serialVersionUID = 153228452;

    private Long       id;
    private String     name;
    private BigDecimal balance;

    public Account() {}

    public Account(Account value) {
        this.id = value.id;
        this.name = value.name;
        this.balance = value.balance;
    }

    public Account(
        Long       id,
        String     name,
        BigDecimal balance
    ) {
        this.id = id;
        this.name = name;
        this.balance = balance;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public BigDecimal getBalance() {
        return this.balance;
    }

    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Account (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(balance);

        sb.append(")");
        return sb.toString();
    }
}
