CREATE TABLE ACCOUNT (
	ID IDENTITY NOT NULL PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL UNIQUE,
);

CREATE TABLE WALLET (
	ID IDENTITY NOT NULL PRIMARY KEY,
	ADDRESS VARCHAR(64) NOT NULL UNIQUE,
	CURRENCY VARCHAR(3) NOT NULL,
	BALANCE DECIMAL(20, 2) NOT NULL DEFAULT 0,
	ACCOUNT_ID BIGINT NOT NULL,
	FOREIGN KEY (ACCOUNT_ID) references ACCOUNT(ID) ON DELETE CASCADE,
  UNIQUE (ADDRESS, CURRENCY)
);

CREATE TABLE TRANSFER (
	ID IDENTITY NOT NULL PRIMARY KEY,
	QUANTITY DECIMAL(20, 2) NOT NULL,
	MOMENT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	EXCHANGE_RATE DOUBLE NOT NULL DEFAULT 1,
	DESCRIPTION VARCHAR(200),
	SENDER_ID BIGINT NOT NULL,
	RECIPIENT_ID BIGINT NOT NULL,
	FOREIGN KEY (SENDER_ID) references WALLET(ID) ON DELETE CASCADE,
	FOREIGN KEY (RECIPIENT_ID) references WALLET(ID) ON DELETE CASCADE
);
