CREATE TABLE ACCOUNT (
	ID IDENTITY NOT NULL PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL UNIQUE, 
);

CREATE TABLE WALLET (
	ID IDENTITY NOT NULL PRIMARY KEY,
	CURRENCY VARCHAR(3) NOT NULL, 
	ADDRESS VARCHAR(64) NOT NULL,
	BALANCE DECIMAL(65535, 2) NOT NULL,
	ACCOUNT_ID BIGINT NOT NULL,
	FOREIGN KEY (ACCOUNT_ID) references ACCOUNT(ID)
);

CREATE TABLE TRANSFER (
	ID IDENTITY NOT NULL PRIMARY KEY,
	QUANTITY DECIMAL(20, 2) NOT NULL,
	EXCHANGE_RATE TINYINT NOT NULL,
	DESCRIPTION VARCHAR(200) NOT NULL,
	SENDER_ID BIGINT NOT NULL,
	RECIPIENT_ID BIGINT NOT NULL,
	FOREIGN KEY (SENDER_ID) references WALLET(ID),
	FOREIGN KEY (RECIPIENT_ID) references WALLET(ID)
);
