/*
 * This file is generated by jOOQ.
 */
package com.hometask.moneytransfer.model.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Wallet implements Serializable {

    private static final long serialVersionUID = 327900414;

    private Long       id;
    private String     currency;
    private String     address;
    private BigDecimal balance;
    private Long       accountId;

    public Wallet() {}

    public Wallet(Wallet value) {
        this.id = value.id;
        this.currency = value.currency;
        this.address = value.address;
        this.balance = value.balance;
        this.accountId = value.accountId;
    }

    public Wallet(
        Long       id,
        String     currency,
        String     address,
        BigDecimal balance,
        Long       accountId
    ) {
        this.id = id;
        this.currency = currency;
        this.address = address;
        this.balance = balance;
        this.accountId = accountId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCurrency() {
        return this.currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public BigDecimal getBalance() {
        return this.balance;
    }

    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    public Long getAccountId() {
        return this.accountId;
    }

    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Wallet (");

        sb.append(id);
        sb.append(", ").append(currency);
        sb.append(", ").append(address);
        sb.append(", ").append(balance);
        sb.append(", ").append(accountId);

        sb.append(")");
        return sb.toString();
    }
}
