/*
 * This file is generated by jOOQ.
 */
package com.hometask.moneytransfer.model.tables.daos;


import com.hometask.moneytransfer.model.tables.Account;
import com.hometask.moneytransfer.model.tables.records.AccountRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountDao extends DAOImpl<AccountRecord, com.hometask.moneytransfer.model.tables.pojos.Account, Long> {

    /**
     * Create a new AccountDao without any configuration
     */
    public AccountDao() {
        super(Account.ACCOUNT, com.hometask.moneytransfer.model.tables.pojos.Account.class);
    }

    /**
     * Create a new AccountDao with an attached configuration
     */
    public AccountDao(Configuration configuration) {
        super(Account.ACCOUNT, com.hometask.moneytransfer.model.tables.pojos.Account.class, configuration);
    }

    @Override
    public Long getId(com.hometask.moneytransfer.model.tables.pojos.Account object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.hometask.moneytransfer.model.tables.pojos.Account> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(Account.ACCOUNT.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.hometask.moneytransfer.model.tables.pojos.Account> fetchById(Long... values) {
        return fetch(Account.ACCOUNT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.hometask.moneytransfer.model.tables.pojos.Account fetchOneById(Long value) {
        return fetchOne(Account.ACCOUNT.ID, value);
    }

    /**
     * Fetch records that have <code>NAME BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.hometask.moneytransfer.model.tables.pojos.Account> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Account.ACCOUNT.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>NAME IN (values)</code>
     */
    public List<com.hometask.moneytransfer.model.tables.pojos.Account> fetchByName(String... values) {
        return fetch(Account.ACCOUNT.NAME, values);
    }

    /**
     * Fetch a unique record that has <code>NAME = value</code>
     */
    public com.hometask.moneytransfer.model.tables.pojos.Account fetchOneByName(String value) {
        return fetchOne(Account.ACCOUNT.NAME, value);
    }
}
