/*
 * This file is generated by jOOQ.
 */
package com.hometask.moneytransfer.model;


import com.hometask.moneytransfer.model.tables.Account;
import com.hometask.moneytransfer.model.tables.Transfer;
import com.hometask.moneytransfer.model.tables.Wallet;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1126620587;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.ACCOUNT</code>.
     */
    public final Account ACCOUNT = com.hometask.moneytransfer.model.tables.Account.ACCOUNT;

    /**
     * The table <code>PUBLIC.TRANSFER</code>.
     */
    public final Transfer TRANSFER = com.hometask.moneytransfer.model.tables.Transfer.TRANSFER;

    /**
     * The table <code>PUBLIC.WALLET</code>.
     */
    public final Wallet WALLET = com.hometask.moneytransfer.model.tables.Wallet.WALLET;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Account.ACCOUNT,
            Transfer.TRANSFER,
            Wallet.WALLET);
    }
}
